const Sequelize = require('sequelize');
const dbConfig = require('../config/database');

const Usuario = require('../models/Usuario');
const Municipio = require('../models/Municipio');
const Categoria = require('../models/Categoria');
const Localidade = require('../models/Localidade');
const Zona = require('../models/Zona');
const Pais = require('../models/Pais');
const Regiao = require('../models/Regiao');
const Estado = require('../models/Estado');
const RegionalSaude = require('../models/RegionalSaude');
const Rua = require('../models/Rua');
const Quarteirao = require('../models/Quarteirao');
const Lado = require('../models/Lado');
const Imovel = require('../models/Imovel');
const Funcao = require('../models/Funcao');
const Atuacao = require('../models/Atuacao');
const Permissao = require('../models/Permissao');
const Metodologia = require('../models/Metodologia');
const Objetivo = require('../models/Objetivo');
const Ciclo = require('../models/Ciclo');
const Atividade = require('../models/Atividade');
const Local = require('../models/Local');
const Estrato = require('../models/Estrato');
const SituacaoQuarteirao = require('../models/SituacaoQuarteirao');
const Equipe = require('../models/Equipe');
const Membro = require('../models/Membro');
const EquipeQuarteirao = require('../models/EquipeQuarteirao');

const connection = new Sequelize(dbConfig);

Usuario.init( connection );
Municipio.init( connection );
Categoria.init( connection );
Localidade.init( connection );
Zona.init( connection );
Pais.init( connection );
Regiao.init( connection );
Estado.init( connection );
RegionalSaude.init( connection );
Rua.init( connection );
Quarteirao.init( connection );
Lado.init( connection );
Imovel.init( connection );
Funcao.init( connection );
Atuacao.init( connection );
Permissao.init( connection );
Metodologia.init( connection );
Objetivo.init( connection );
Ciclo.init( connection );
Atividade.init( connection );
Local.init( connection );
Estrato.init( connection );
SituacaoQuarteirao.init( connection );
Equipe.init( connection );
Membro.init( connection );
EquipeQuarteirao.init( connection );

Usuario.associate( connection.models );
Municipio.associate( connection.models );
Categoria.associate( connection.models );
Localidade.associate( connection.models );
Zona.associate( connection.models );
Pais.associate( connection.models );
Regiao.associate( connection.models );
Estado.associate( connection.models );
RegionalSaude.associate( connection.models );
Rua.associate( connection.models );
Quarteirao.associate( connection.models );
Lado.associate( connection.models );
Imovel.associate( connection.models );
Funcao.associate( connection.models );
Atuacao.associate( connection.models );
Permissao.associate( connection.models );
Metodologia.associate( connection.models );
Objetivo.associate( connection.models );
Ciclo.associate( connection.models );
Atividade.associate( connection.models );
Local.associate( connection.models );
Estrato.associate( connection.models );
SituacaoQuarteirao.associate( connection.models );
Equipe.associate( connection.models );
Membro.associate( connection.models );
EquipeQuarteirao.associate( connection.models );

module.exports = connection;